### ISSUE TITLE
[VRChatUtilityKit] [ERROR] Exception during OnApplicationStart

### ISSUE THREAD

**Issue by Chroxer** [SleepyVRC/Mods#24] opened 2022-02-23 19:57 UTC
```
[VRChatUtilityKit] [ERROR] Exception during OnApplicationStart:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Parent class failed to load, due to: Could not load type of field 'PlayerList.Entries.PlayerEntry:perf' (11) due to: Could not resolve type with token 0100004b (from typeref, class/assembly VRC.DataModel.AvatarPerformanceRating, DataModel, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:DataModel, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:VRC.DataModel.AvatarPerformanceRating member:(null) signature:<none> assembly:data-00000158740CE860 type:PlayerEntry member:(null) signature:<none>

  at (wrapper managed-to-native) System.RuntimeType.GetMethodsByName_native(System.RuntimeType,intptr,System.Reflection.BindingFlags,bool)

  at System.RuntimeType.GetMethodsByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.Boolean ignoreCase, System.RuntimeType reflectedType) [0x0001b] in <e1319b7195c343e79b385cd3aa43f5dc>:0 

  at System.RuntimeType.GetMethodCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.CallingConventions callConv, System.Type[] types, System.Boolean allowPrefixLookup) [0x00010] in <e1319b7195c343e79b385cd3aa43f5dc>:0 

  at System.RuntimeType.GetMethods (System.Reflection.BindingFlags bindingAttr) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 

  at VRChatUtilityKit.Utilities.KeybindAttribute+<>c.<OnApplicationStart>b__6_2 (System.Type type) [0x00000] in <b5e6a06bb53647b2b9cd4357b3b6c332>:0 

  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00051] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 

  at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].ToArray () [0x0003e] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 

  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 

  at VRChatUtilityKit.Utilities.KeybindAttribute.OnApplicationStart () [0x000b9] in <b5e6a06bb53647b2b9cd4357b3b6c332>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e1319b7195c343e79b385cd3aa43f5dc>:0 

   --- End of inner exception stack trace ---

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <e1319b7195c343e79b385cd3aa43f5dc>:0 

  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 

  at VRChatUtilityKit.VRChatUtilityKitMod.OnApplicationStart () [0x0012f] in <b5e6a06bb53647b2b9cd4357b3b6c332>:0 
```

**Comment by ljoonal** [comment] 2022-02-24 02:06
This isn't reproducible without more info.
Have you made sure that you're running the latest version of VRChatUtilityKit and the latest version of MelonLoader?
And running the latest non-beta version of VRC?

**Comment by ljoonal** [comment] 2022-02-27 06:31
Closing due to no reply and this seeming to also be related more to `PlayerList` than to VRCUK.

**Closed by ljoonal** 2022-02-27 06:31 UTC
